### ISSUE TITLE
C3 and scatterD3 incompatibility?

### ISSUE THREAD

**Issue by Tixierae** [FrissAnalytics/shinyJsTutorials#16]
The following minimal reproducible example works fine, but when I uncomment `scatterD3Output("scatterPlot", height = "700px")` it stops working: **no error is given, but no output is shown**. 

Are the C3 and scatterD3 libraries incompatible? Thanks much in advance for any help.

    library(shiny)
    library(C3)
    library(scatterD3)
    
    server = function(input, output) {
      my_df = reactive({
        input$button
        my_df = list(a=runif(1,0,100),b=runif(1,0,100),c=runif(1,0,100))
        list(my_df=my_df)
      })
      output$my_pie = renderC3Pie({
        C3Pie(value = my_df()$my_df)
      })
      output$scatterPlot <- renderScatterD3({
        scatterD3(x=1,y=1)
      })
    }
        
    ui = shinyUI(
      fluidPage(
        fluidRow(
          actionButton('button', "Draw!"),
          C3PieOutput('my_pie')
        ),
        fluidRow(
          br()#,scatterD3Output("scatterPlot", height = "700px")
        )
      )
    )
    shinyApp(ui = ui, server = server)

**Comment by FrissAnalytics** [comment]
Hi,

the tutorial series code uses v3.x of d3.js. I just briefly checked the repo you mentioned, which seems to use v4.x of d3.js (see, [here](https://github.com/juba/scatterD3/blob/master/inst/htmlwidgets/scatterD3.yaml)) . 

Code based on the v4 series is,unfortunately, not compatible with the older v3 series . This is due to the fact that most of the namespace of d3.js has changed. See [here](https://iros.github.io/d3-v4-whats-new/#1) for some more info on this. 

Of note, c3.js itself is based on d3.js version v3. There is a fork of c3.js, called [billboard.js](https://naver.github.io/billboard.js/), that uses d3.js v4.x instead. 

The syntax of [billboard.js](https://naver.github.io/billboard.js/), however, is mostly identical to the syntax used by c3.js. Hence, updating the code snippets in our tutorials to work with billboard.js is not that hard. I believe such changes will lead to a code base in which you can use scatterD3 in combination with billboard.js based charts, which have the exact same look and capabilities of c3.js charts.

**Comment by Tixierae** [comment]
Thank you very much for identifying the source of the problem so quickly. I will try what you propose.
It might not be the best option, but would this work by any chance?: https://stackoverflow.com/questions/44173693/using-different-d3-versions-on-same-html-page/44175745#44175745

**Comment by FrissAnalytics** [comment]
I've approached RSTUDIO a while back how best to deal with such version conflict issues, but they believe it's difficult to get a good solution.

I've never attempted what you suggest above but perhaps it works :-) Still, I feel the best way is to update the code snippets and to work with version 4.x of d3.js as that is the future of d3.

Unfortunately, there is a ton of code examples that all work with d3.js v3.x code, so unless all of those people behind such projects update their code it will be hard to find a satisfactory solution.

**Comment by Tixierae** [comment]
Just FYI, the maintainer of the `scatterD3` library made it work by using the solution in my stack overflow link above (see https://github.com/juba/scatterD3/issues/67).
It's good to know that such an easy fix can do the job!
